### ISSUE TITLE
WebSocket DISCONNECT /ws/notif/ [127.0.0.1:63856]

### ISSUE THREAD

**Issue by lillois59** [gibran-abdillah/chat-app#1]
Hi @gibran-abdillah I use you djando template look awesone, so I got problem when I send my first message .

after creating bot and running server everything look good seam working, yes but when I send message igot this :

 File "/Users/Apple/Desktop/chat-app/lib/python3.10/site-packages/channels/layers.py", line 69, in _make_backend
    raise InvalidChannelLayerError(
channels.exceptions.InvalidChannelLayerError: Cannot import BACKEND 'channels_redis.core.RedisChannelLayer' specified for default
WebSocket DISCONNECT /ws/notif/ [127.0.0.1:63856]

what do think I missed to do?

**Comment by gibran-abdillah** [comment]
hey, try to install the channels_redis module

```sh
pip3 install channels_redis
```

**Comment by lillois59** [comment]
File "/Users/Apple/Desktop/chat-app/env/lib/python3.10/site-packages/redis/asyncio/connection.py", line 252, in read_response

    raise InvalidResponse(f"Protocol Error: {raw!r}")

redis.exceptions.InvalidResponse: Protocol Error: b'HTTP/1.1 400 Bad Request'

 still not working
________________________________
De : gibran abdillah ***@***.***>
Envoyé : dimanche 4 décembre 2022 15:12
À : gibran-abdillah/chat-app ***@***.***>
Cc : lillois ***@***.***>; Author ***@***.***>
Objet : Re: [gibran-abdillah/chat-app] WebSocket DISCONNECT /ws/notif/ [127.0.0.1:63856] (Issue #1)


Closed #1<https://github.com/gibran-abdillah/chat-app/issues/1> as completed.

**Comment by gibran-abdillah** [comment]
what is the port for the redis-server?

**Comment by lillois59** [comment]
"hosts" :[('localhost', 8000)],
}
}

**Comment by gibran-abdillah** [comment]
the port you are using collides with the port used http. try using another port for redis server :D
